services:
  inventory:
    build:
      context: ../..
      dockerfile: apps/inventory/Dockerfile
    container_name: inventory
    restart: unless-stopped
    labels:
      homeport.group: internal
    volumes:
      - ./data:/data
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
