services:
  infra:
    build:
      context: ../..
      dockerfile: apps/infra/Dockerfile
    container_name: infra
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOZZLE_URL=${DOZZLE_URL:-}
      - OWN_NAME=infra
      - HOSTNAME_DISPLAY=${HOSTNAME_DISPLAY:-station}
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
