services:
  hub:
    build:
      context: ../..
      dockerfile: apps/hub/Dockerfile
    container_name: hub
    restart: unless-stopped
    labels:
      homeport.group: internal
    volumes:
      - ./dashboard.json:/app/dashboard.json
    environment:
      - HOSTNAME_DISPLAY=station
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
